### ISSUE TITLE
Installation error for julia v"1.0.3"

### ISSUE THREAD

**Issue by yijiangh** [danspielman/Laplacians.jl#16]
I'm using Julia v 1.0.3 on Mac Mojave 10.14.3. The README in this repo says this package supports Julia v1.0.0. And I suppose it should support v1.0.3 as well. 

But when I tried to install it using the package manager, the following error showed up: 

```
(v1.0) pkg> add Laplacians#master
  Updating git-repo `https://github.com/danspielman/Laplacians.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:
 DebuggerFramework [67417a49] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.2
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.4] or uninstalled
 │   └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

I'm wondering if anyone has encountered a similar problem? Am I missing something here? 

Thanks in advance!

**Comment by danspielman** [comment]
I honestly have no idea why this is trying to install DebuggerFramework.
Laplacians does not call for it.

Maybe it would make sense to try updating all of your other packages before installing Laplacians.

**Comment by yijiangh** [comment]
Thank you for your reply! 

Indeed as you said, an update of all the packages will fix this problem: `]update` in your julia terminal.
