### ISSUE TITLE
Inexact error using fiedler

### ISSUE THREAD

**Issue by narayanivedam** [danspielman/Laplacians.jl#20]
I have raised an issue that I face in the julialanguage forum [here](https://discourse.julialang.org/t/using-laplacians-to-find-fiedler-values/32907?u=ennvvy). It would be great if I could know the reason for this error.

**Comment by danspielman** [comment]
It seems that the `fiedler` function requires a matrix of Floats.
You could construct one instead writing
`a = Float64.(adjacency_matrix(g))`
