### ISSUE TITLE
Simple test failure on Julia 1.4 with cholmod defaults on common_struct due to threading changes

### ISSUE THREAD

**Issue by dgleich** [danspielman/Laplacians.jl#23]
Running Pkg.test on Julia 1.4 gives an error when getting default parameters in Cholmod. This occurs because of some changes due to Threading in Julia where common_struct is now allocated per thread. The fix is simple.

Replace line 22 and line 52 in `src/from_cholmod.jl` with

    cm = ba.defaults(ba.common_struct[Threads.threadid()])

After that change, tests pass for me on 1.4.1. Happy to submit a pull request, but that seems like much more work than needed for a very simple change! 

This does not work under 1.3, however, so if you want backwards compat, then you might need an 

    @static if VERSION >= v"1.4"
        cm = ba.defaults(ba.common_struct[Threads.threadid()])
    else
        cm = ba.defaults(ba.common_struct)
    end

This works under 1.3 and 1.4.

**Comment by danspielman** [comment]
Thanks for the suggestion.
I'm putting this in now.
