### ISSUE TITLE
Julia 0.5 incompabitilities

### ISSUE THREAD

**Issue by DoliathGavid** [danspielman/Laplacians.jl#4]
I'm relatively new to Julia and I've noticed that the mapweight is now breaking for all the examples shown:

```
m = grid2(100)
a = mapweight(m,x->1/(rand(1)[1]));

LoadError: type SparseMatrixCSC is immutable
while loading In[19], in expression starting on line 2

 in mapweight(::SparseMatrixCSC{Float64,Int64}, ::Function) at /Laplacians/src/graphOps.jl:49
```

**Comment by danspielman** [comment]
This works for us.
Make sure that you are using version 0.5.0 of Julia,
and the current version of Laplacians.
If you are not sure, then you can update it by
Pkg.checkout("Laplacians")

**Comment by DoliathGavid** [comment]
closing this for now.
